INITRD_TAR := $(subdir)/initrd.tar
INITRD_INITRD := $(subdir)/initrd
INITRD_INITRD_DEVFS = $(INITRD_INITRD)/devfs
INITRD_INITRD_SBIN = $(INITRD_INITRD)/sbin
INITRD_INITRD_FATFS = $(INITRD_INITRD)/fatfs
INITRD_INITRD_SYMBOL_MAP = $(INITRD_INITRD)/symbol.map

$(INITRD_INITRD_SYMBOL_MAP): $(KERNEL)
	nm $(KERNEL) | grep -i ' t ' > $(INITRD_INITRD_SYMBOL_MAP)

$(INITRD_TAR): $(INITRD_SBIN) $(INITRD_INITRD_SYMBOL_MAP)
	cp -f $(INITRD_SBIN) $(INITRD_INITRD_SBIN)
	( cd $(INITRD_INITRD) && tar -cf - * ) > $(INITRD_TAR)

includes::
	mkdir -p $(INITRD_INITRD_SBIN) $(INITRD_INITRD_DEVFS) $(INITRD_INITRD_FATFS)

clean::
	rm -rf $(INITRD_INITRD) $(TARFS_TAR)
