.global isr_0
.type isr_0, @function
isr_0:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $0
	jmp isr

.global isr_1
.type isr_1, @function
isr_1:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $1
	jmp isr

.global isr_2
.type isr_2, @function
isr_2:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $2
	jmp isr

.global isr_3
.type isr_3, @function
isr_3:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $3
	jmp isr

.global isr_4
.type isr_4, @function
isr_4:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $4
	jmp isr

.global isr_5
.type isr_5, @function
isr_5:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $5
	jmp isr

.global isr_6
.type isr_6, @function
isr_6:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $6
	jmp isr

.global isr_7
.type isr_7, @function
isr_7:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $7
	jmp isr

.global isr_8
.type isr_8, @function
isr_8:
	pushl %ds
	pushal
	pushl %esp
	pushl $8
	jmp isr

.global isr_9
.type isr_9, @function
isr_9:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $9
	jmp isr

.global isr_10
.type isr_10, @function
isr_10:
	pushl %ds
	pushal
	pushl %esp
	pushl $10
	jmp isr

.global isr_11
.type isr_11, @function
isr_11:
	pushl %ds
	pushal
	pushl %esp
	pushl $11
	jmp isr

.global isr_12
.type isr_12, @function
isr_12:
	pushl %ds
	pushal
	pushl %esp
	pushl $12
	jmp isr

.global isr_13
.type isr_13, @function
isr_13:
	pushl %ds
	pushal
	pushl %esp
	pushl $13
	jmp isr

.global isr_14
.type isr_14, @function
isr_14:
	pushl %ds
	pushal
	pushl %esp
	pushl $14
	jmp isr

.global isr_15
.type isr_15, @function
isr_15:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $15
	jmp isr

.global isr_16
.type isr_16, @function
isr_16:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $16
	jmp isr

.global isr_17
.type isr_17, @function
isr_17:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $17
	jmp isr

.global isr_18
.type isr_18, @function
isr_18:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $18
	jmp isr

.global isr_19
.type isr_19, @function
isr_19:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $19
	jmp isr

.global isr_20
.type isr_20, @function
isr_20:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $20
	jmp isr

.global isr_21
.type isr_21, @function
isr_21:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $21
	jmp isr

.global isr_22
.type isr_22, @function
isr_22:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $22
	jmp isr

.global isr_23
.type isr_23, @function
isr_23:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $23
	jmp isr

.global isr_24
.type isr_24, @function
isr_24:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $24
	jmp isr

.global isr_25
.type isr_25, @function
isr_25:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $25
	jmp isr

.global isr_26
.type isr_26, @function
isr_26:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $26
	jmp isr

.global isr_27
.type isr_27, @function
isr_27:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $27
	jmp isr

.global isr_28
.type isr_28, @function
isr_28:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $28
	jmp isr

.global isr_29
.type isr_29, @function
isr_29:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $29
	jmp isr

.global isr_30
.type isr_30, @function
isr_30:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $30
	jmp isr

.global isr_31
.type isr_31, @function
isr_31:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $31
	jmp isr

.global isr_32
.type isr_32, @function
isr_32:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $32
	jmp isr

.global isr_33
.type isr_33, @function
isr_33:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $33
	jmp isr

.global isr_34
.type isr_34, @function
isr_34:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $34
	jmp isr

.global isr_35
.type isr_35, @function
isr_35:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $35
	jmp isr

.global isr_36
.type isr_36, @function
isr_36:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $36
	jmp isr

.global isr_37
.type isr_37, @function
isr_37:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $37
	jmp isr

.global isr_38
.type isr_38, @function
isr_38:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $38
	jmp isr

.global isr_39
.type isr_39, @function
isr_39:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $39
	jmp isr

.global isr_40
.type isr_40, @function
isr_40:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $40
	jmp isr

.global isr_41
.type isr_41, @function
isr_41:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $41
	jmp isr

.global isr_42
.type isr_42, @function
isr_42:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $42
	jmp isr

.global isr_43
.type isr_43, @function
isr_43:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $43
	jmp isr

.global isr_44
.type isr_44, @function
isr_44:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $44
	jmp isr

.global isr_45
.type isr_45, @function
isr_45:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $45
	jmp isr

.global isr_46
.type isr_46, @function
isr_46:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $46
	jmp isr

.global isr_47
.type isr_47, @function
isr_47:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $47
	jmp isr

.global isr_48
.type isr_48, @function
isr_48:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $48
	jmp isr

.global isr_49
.type isr_49, @function
isr_49:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $49
	jmp isr

.global isr_50
.type isr_50, @function
isr_50:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $50
	jmp isr

.global isr_51
.type isr_51, @function
isr_51:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $51
	jmp isr

.global isr_52
.type isr_52, @function
isr_52:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $52
	jmp isr

.global isr_53
.type isr_53, @function
isr_53:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $53
	jmp isr

.global isr_54
.type isr_54, @function
isr_54:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $54
	jmp isr

.global isr_55
.type isr_55, @function
isr_55:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $55
	jmp isr

.global isr_56
.type isr_56, @function
isr_56:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $56
	jmp isr

.global isr_57
.type isr_57, @function
isr_57:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $57
	jmp isr

.global isr_58
.type isr_58, @function
isr_58:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $58
	jmp isr

.global isr_59
.type isr_59, @function
isr_59:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $59
	jmp isr

.global isr_60
.type isr_60, @function
isr_60:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $60
	jmp isr

.global isr_61
.type isr_61, @function
isr_61:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $61
	jmp isr

.global isr_62
.type isr_62, @function
isr_62:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $62
	jmp isr

.global isr_63
.type isr_63, @function
isr_63:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $63
	jmp isr

.global isr_64
.type isr_64, @function
isr_64:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $64
	jmp isr

.global isr_65
.type isr_65, @function
isr_65:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $65
	jmp isr

.global isr_66
.type isr_66, @function
isr_66:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $66
	jmp isr

.global isr_67
.type isr_67, @function
isr_67:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $67
	jmp isr

.global isr_68
.type isr_68, @function
isr_68:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $68
	jmp isr

.global isr_69
.type isr_69, @function
isr_69:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $69
	jmp isr

.global isr_70
.type isr_70, @function
isr_70:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $70
	jmp isr

.global isr_71
.type isr_71, @function
isr_71:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $71
	jmp isr

.global isr_72
.type isr_72, @function
isr_72:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $72
	jmp isr

.global isr_73
.type isr_73, @function
isr_73:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $73
	jmp isr

.global isr_74
.type isr_74, @function
isr_74:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $74
	jmp isr

.global isr_75
.type isr_75, @function
isr_75:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $75
	jmp isr

.global isr_76
.type isr_76, @function
isr_76:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $76
	jmp isr

.global isr_77
.type isr_77, @function
isr_77:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $77
	jmp isr

.global isr_78
.type isr_78, @function
isr_78:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $78
	jmp isr

.global isr_79
.type isr_79, @function
isr_79:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $79
	jmp isr

.global isr_80
.type isr_80, @function
isr_80:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $80
	jmp isr

.global isr_81
.type isr_81, @function
isr_81:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $81
	jmp isr

.global isr_82
.type isr_82, @function
isr_82:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $82
	jmp isr

.global isr_83
.type isr_83, @function
isr_83:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $83
	jmp isr

.global isr_84
.type isr_84, @function
isr_84:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $84
	jmp isr

.global isr_85
.type isr_85, @function
isr_85:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $85
	jmp isr

.global isr_86
.type isr_86, @function
isr_86:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $86
	jmp isr

.global isr_87
.type isr_87, @function
isr_87:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $87
	jmp isr

.global isr_88
.type isr_88, @function
isr_88:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $88
	jmp isr

.global isr_89
.type isr_89, @function
isr_89:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $89
	jmp isr

.global isr_90
.type isr_90, @function
isr_90:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $90
	jmp isr

.global isr_91
.type isr_91, @function
isr_91:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $91
	jmp isr

.global isr_92
.type isr_92, @function
isr_92:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $92
	jmp isr

.global isr_93
.type isr_93, @function
isr_93:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $93
	jmp isr

.global isr_94
.type isr_94, @function
isr_94:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $94
	jmp isr

.global isr_95
.type isr_95, @function
isr_95:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $95
	jmp isr

.global isr_96
.type isr_96, @function
isr_96:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $96
	jmp isr

.global isr_97
.type isr_97, @function
isr_97:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $97
	jmp isr

.global isr_98
.type isr_98, @function
isr_98:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $98
	jmp isr

.global isr_99
.type isr_99, @function
isr_99:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $99
	jmp isr

.global isr_100
.type isr_100, @function
isr_100:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $100
	jmp isr

.global isr_101
.type isr_101, @function
isr_101:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $101
	jmp isr

.global isr_102
.type isr_102, @function
isr_102:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $102
	jmp isr

.global isr_103
.type isr_103, @function
isr_103:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $103
	jmp isr

.global isr_104
.type isr_104, @function
isr_104:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $104
	jmp isr

.global isr_105
.type isr_105, @function
isr_105:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $105
	jmp isr

.global isr_106
.type isr_106, @function
isr_106:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $106
	jmp isr

.global isr_107
.type isr_107, @function
isr_107:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $107
	jmp isr

.global isr_108
.type isr_108, @function
isr_108:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $108
	jmp isr

.global isr_109
.type isr_109, @function
isr_109:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $109
	jmp isr

.global isr_110
.type isr_110, @function
isr_110:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $110
	jmp isr

.global isr_111
.type isr_111, @function
isr_111:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $111
	jmp isr

.global isr_112
.type isr_112, @function
isr_112:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $112
	jmp isr

.global isr_113
.type isr_113, @function
isr_113:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $113
	jmp isr

.global isr_114
.type isr_114, @function
isr_114:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $114
	jmp isr

.global isr_115
.type isr_115, @function
isr_115:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $115
	jmp isr

.global isr_116
.type isr_116, @function
isr_116:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $116
	jmp isr

.global isr_117
.type isr_117, @function
isr_117:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $117
	jmp isr

.global isr_118
.type isr_118, @function
isr_118:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $118
	jmp isr

.global isr_119
.type isr_119, @function
isr_119:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $119
	jmp isr

.global isr_120
.type isr_120, @function
isr_120:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $120
	jmp isr

.global isr_121
.type isr_121, @function
isr_121:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $121
	jmp isr

.global isr_122
.type isr_122, @function
isr_122:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $122
	jmp isr

.global isr_123
.type isr_123, @function
isr_123:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $123
	jmp isr

.global isr_124
.type isr_124, @function
isr_124:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $124
	jmp isr

.global isr_125
.type isr_125, @function
isr_125:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $125
	jmp isr

.global isr_126
.type isr_126, @function
isr_126:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $126
	jmp isr

.global isr_127
.type isr_127, @function
isr_127:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $127
	jmp isr

.global isr_128
.type isr_128, @function
isr_128:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $128
	jmp isr

.global isr_129
.type isr_129, @function
isr_129:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $129
	jmp isr

.global isr_130
.type isr_130, @function
isr_130:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $130
	jmp isr

.global isr_131
.type isr_131, @function
isr_131:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $131
	jmp isr

.global isr_132
.type isr_132, @function
isr_132:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $132
	jmp isr

.global isr_133
.type isr_133, @function
isr_133:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $133
	jmp isr

.global isr_134
.type isr_134, @function
isr_134:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $134
	jmp isr

.global isr_135
.type isr_135, @function
isr_135:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $135
	jmp isr

.global isr_136
.type isr_136, @function
isr_136:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $136
	jmp isr

.global isr_137
.type isr_137, @function
isr_137:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $137
	jmp isr

.global isr_138
.type isr_138, @function
isr_138:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $138
	jmp isr

.global isr_139
.type isr_139, @function
isr_139:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $139
	jmp isr

.global isr_140
.type isr_140, @function
isr_140:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $140
	jmp isr

.global isr_141
.type isr_141, @function
isr_141:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $141
	jmp isr

.global isr_142
.type isr_142, @function
isr_142:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $142
	jmp isr

.global isr_143
.type isr_143, @function
isr_143:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $143
	jmp isr

.global isr_144
.type isr_144, @function
isr_144:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $144
	jmp isr

.global isr_145
.type isr_145, @function
isr_145:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $145
	jmp isr

.global isr_146
.type isr_146, @function
isr_146:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $146
	jmp isr

.global isr_147
.type isr_147, @function
isr_147:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $147
	jmp isr

.global isr_148
.type isr_148, @function
isr_148:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $148
	jmp isr

.global isr_149
.type isr_149, @function
isr_149:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $149
	jmp isr

.global isr_150
.type isr_150, @function
isr_150:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $150
	jmp isr

.global isr_151
.type isr_151, @function
isr_151:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $151
	jmp isr

.global isr_152
.type isr_152, @function
isr_152:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $152
	jmp isr

.global isr_153
.type isr_153, @function
isr_153:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $153
	jmp isr

.global isr_154
.type isr_154, @function
isr_154:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $154
	jmp isr

.global isr_155
.type isr_155, @function
isr_155:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $155
	jmp isr

.global isr_156
.type isr_156, @function
isr_156:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $156
	jmp isr

.global isr_157
.type isr_157, @function
isr_157:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $157
	jmp isr

.global isr_158
.type isr_158, @function
isr_158:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $158
	jmp isr

.global isr_159
.type isr_159, @function
isr_159:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $159
	jmp isr

.global isr_160
.type isr_160, @function
isr_160:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $160
	jmp isr

.global isr_161
.type isr_161, @function
isr_161:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $161
	jmp isr

.global isr_162
.type isr_162, @function
isr_162:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $162
	jmp isr

.global isr_163
.type isr_163, @function
isr_163:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $163
	jmp isr

.global isr_164
.type isr_164, @function
isr_164:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $164
	jmp isr

.global isr_165
.type isr_165, @function
isr_165:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $165
	jmp isr

.global isr_166
.type isr_166, @function
isr_166:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $166
	jmp isr

.global isr_167
.type isr_167, @function
isr_167:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $167
	jmp isr

.global isr_168
.type isr_168, @function
isr_168:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $168
	jmp isr

.global isr_169
.type isr_169, @function
isr_169:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $169
	jmp isr

.global isr_170
.type isr_170, @function
isr_170:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $170
	jmp isr

.global isr_171
.type isr_171, @function
isr_171:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $171
	jmp isr

.global isr_172
.type isr_172, @function
isr_172:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $172
	jmp isr

.global isr_173
.type isr_173, @function
isr_173:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $173
	jmp isr

.global isr_174
.type isr_174, @function
isr_174:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $174
	jmp isr

.global isr_175
.type isr_175, @function
isr_175:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $175
	jmp isr

.global isr_176
.type isr_176, @function
isr_176:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $176
	jmp isr

.global isr_177
.type isr_177, @function
isr_177:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $177
	jmp isr

.global isr_178
.type isr_178, @function
isr_178:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $178
	jmp isr

.global isr_179
.type isr_179, @function
isr_179:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $179
	jmp isr

.global isr_180
.type isr_180, @function
isr_180:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $180
	jmp isr

.global isr_181
.type isr_181, @function
isr_181:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $181
	jmp isr

.global isr_182
.type isr_182, @function
isr_182:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $182
	jmp isr

.global isr_183
.type isr_183, @function
isr_183:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $183
	jmp isr

.global isr_184
.type isr_184, @function
isr_184:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $184
	jmp isr

.global isr_185
.type isr_185, @function
isr_185:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $185
	jmp isr

.global isr_186
.type isr_186, @function
isr_186:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $186
	jmp isr

.global isr_187
.type isr_187, @function
isr_187:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $187
	jmp isr

.global isr_188
.type isr_188, @function
isr_188:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $188
	jmp isr

.global isr_189
.type isr_189, @function
isr_189:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $189
	jmp isr

.global isr_190
.type isr_190, @function
isr_190:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $190
	jmp isr

.global isr_191
.type isr_191, @function
isr_191:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $191
	jmp isr

.global isr_192
.type isr_192, @function
isr_192:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $192
	jmp isr

.global isr_193
.type isr_193, @function
isr_193:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $193
	jmp isr

.global isr_194
.type isr_194, @function
isr_194:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $194
	jmp isr

.global isr_195
.type isr_195, @function
isr_195:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $195
	jmp isr

.global isr_196
.type isr_196, @function
isr_196:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $196
	jmp isr

.global isr_197
.type isr_197, @function
isr_197:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $197
	jmp isr

.global isr_198
.type isr_198, @function
isr_198:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $198
	jmp isr

.global isr_199
.type isr_199, @function
isr_199:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $199
	jmp isr

.global isr_200
.type isr_200, @function
isr_200:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $200
	jmp isr

.global isr_201
.type isr_201, @function
isr_201:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $201
	jmp isr

.global isr_202
.type isr_202, @function
isr_202:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $202
	jmp isr

.global isr_203
.type isr_203, @function
isr_203:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $203
	jmp isr

.global isr_204
.type isr_204, @function
isr_204:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $204
	jmp isr

.global isr_205
.type isr_205, @function
isr_205:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $205
	jmp isr

.global isr_206
.type isr_206, @function
isr_206:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $206
	jmp isr

.global isr_207
.type isr_207, @function
isr_207:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $207
	jmp isr

.global isr_208
.type isr_208, @function
isr_208:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $208
	jmp isr

.global isr_209
.type isr_209, @function
isr_209:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $209
	jmp isr

.global isr_210
.type isr_210, @function
isr_210:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $210
	jmp isr

.global isr_211
.type isr_211, @function
isr_211:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $211
	jmp isr

.global isr_212
.type isr_212, @function
isr_212:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $212
	jmp isr

.global isr_213
.type isr_213, @function
isr_213:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $213
	jmp isr

.global isr_214
.type isr_214, @function
isr_214:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $214
	jmp isr

.global isr_215
.type isr_215, @function
isr_215:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $215
	jmp isr

.global isr_216
.type isr_216, @function
isr_216:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $216
	jmp isr

.global isr_217
.type isr_217, @function
isr_217:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $217
	jmp isr

.global isr_218
.type isr_218, @function
isr_218:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $218
	jmp isr

.global isr_219
.type isr_219, @function
isr_219:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $219
	jmp isr

.global isr_220
.type isr_220, @function
isr_220:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $220
	jmp isr

.global isr_221
.type isr_221, @function
isr_221:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $221
	jmp isr

.global isr_222
.type isr_222, @function
isr_222:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $222
	jmp isr

.global isr_223
.type isr_223, @function
isr_223:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $223
	jmp isr

.global isr_224
.type isr_224, @function
isr_224:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $224
	jmp isr

.global isr_225
.type isr_225, @function
isr_225:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $225
	jmp isr

.global isr_226
.type isr_226, @function
isr_226:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $226
	jmp isr

.global isr_227
.type isr_227, @function
isr_227:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $227
	jmp isr

.global isr_228
.type isr_228, @function
isr_228:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $228
	jmp isr

.global isr_229
.type isr_229, @function
isr_229:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $229
	jmp isr

.global isr_230
.type isr_230, @function
isr_230:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $230
	jmp isr

.global isr_231
.type isr_231, @function
isr_231:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $231
	jmp isr

.global isr_232
.type isr_232, @function
isr_232:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $232
	jmp isr

.global isr_233
.type isr_233, @function
isr_233:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $233
	jmp isr

.global isr_234
.type isr_234, @function
isr_234:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $234
	jmp isr

.global isr_235
.type isr_235, @function
isr_235:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $235
	jmp isr

.global isr_236
.type isr_236, @function
isr_236:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $236
	jmp isr

.global isr_237
.type isr_237, @function
isr_237:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $237
	jmp isr

.global isr_238
.type isr_238, @function
isr_238:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $238
	jmp isr

.global isr_239
.type isr_239, @function
isr_239:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $239
	jmp isr

.global isr_240
.type isr_240, @function
isr_240:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $240
	jmp isr

.global isr_241
.type isr_241, @function
isr_241:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $241
	jmp isr

.global isr_242
.type isr_242, @function
isr_242:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $242
	jmp isr

.global isr_243
.type isr_243, @function
isr_243:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $243
	jmp isr

.global isr_244
.type isr_244, @function
isr_244:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $244
	jmp isr

.global isr_245
.type isr_245, @function
isr_245:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $245
	jmp isr

.global isr_246
.type isr_246, @function
isr_246:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $246
	jmp isr

.global isr_247
.type isr_247, @function
isr_247:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $247
	jmp isr

.global isr_248
.type isr_248, @function
isr_248:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $248
	jmp isr

.global isr_249
.type isr_249, @function
isr_249:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $249
	jmp isr

.global isr_250
.type isr_250, @function
isr_250:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $250
	jmp isr

.global isr_251
.type isr_251, @function
isr_251:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $251
	jmp isr

.global isr_252
.type isr_252, @function
isr_252:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $252
	jmp isr

.global isr_253
.type isr_253, @function
isr_253:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $253
	jmp isr

.global isr_254
.type isr_254, @function
isr_254:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $254
	jmp isr

.global isr_255
.type isr_255, @function
isr_255:
	push $0
	pushl %ds
	pushal
	pushl %esp
	pushl $255
	jmp isr

