.global isr_0
isr_0:
	pushal
	pushl %esp
	pushl $0
	jmp isr

.global isr_1
isr_1:
	pushal
	pushl %esp
	pushl $1
	jmp isr

.global isr_2
isr_2:
	pushal
	pushl %esp
	pushl $2
	jmp isr

.global isr_3
isr_3:
	pushal
	pushl %esp
	pushl $3
	jmp isr

.global isr_4
isr_4:
	pushal
	pushl %esp
	pushl $4
	jmp isr

.global isr_5
isr_5:
	pushal
	pushl %esp
	pushl $5
	jmp isr

.global isr_6
isr_6:
	pushal
	pushl %esp
	pushl $6
	jmp isr

.global isr_7
isr_7:
	pushal
	pushl %esp
	pushl $7
	jmp isr

.global isr_8
isr_8:
	pushal
	pushl %esp
	pushl $8
	jmp isr

.global isr_9
isr_9:
	pushal
	pushl %esp
	pushl $9
	jmp isr

.global isr_10
isr_10:
	pushal
	pushl %esp
	pushl $10
	jmp isr

.global isr_11
isr_11:
	pushal
	pushl %esp
	pushl $11
	jmp isr

.global isr_12
isr_12:
	pushal
	pushl %esp
	pushl $12
	jmp isr

.global isr_13
isr_13:
	pushal
	pushl %esp
	pushl $13
	jmp isr

.global isr_14
isr_14:
	pushal
	pushl %esp
	pushl $14
	jmp isr

.global isr_15
isr_15:
	pushal
	pushl %esp
	pushl $15
	jmp isr

.global isr_16
isr_16:
	pushal
	pushl %esp
	pushl $16
	jmp isr

.global isr_17
isr_17:
	pushal
	pushl %esp
	pushl $17
	jmp isr

.global isr_18
isr_18:
	pushal
	pushl %esp
	pushl $18
	jmp isr

.global isr_19
isr_19:
	pushal
	pushl %esp
	pushl $19
	jmp isr

.global isr_20
isr_20:
	pushal
	pushl %esp
	pushl $20
	jmp isr

.global isr_21
isr_21:
	pushal
	pushl %esp
	pushl $21
	jmp isr

.global isr_22
isr_22:
	pushal
	pushl %esp
	pushl $22
	jmp isr

.global isr_23
isr_23:
	pushal
	pushl %esp
	pushl $23
	jmp isr

.global isr_24
isr_24:
	pushal
	pushl %esp
	pushl $24
	jmp isr

.global isr_25
isr_25:
	pushal
	pushl %esp
	pushl $25
	jmp isr

.global isr_26
isr_26:
	pushal
	pushl %esp
	pushl $26
	jmp isr

.global isr_27
isr_27:
	pushal
	pushl %esp
	pushl $27
	jmp isr

.global isr_28
isr_28:
	pushal
	pushl %esp
	pushl $28
	jmp isr

.global isr_29
isr_29:
	pushal
	pushl %esp
	pushl $29
	jmp isr

.global isr_30
isr_30:
	pushal
	pushl %esp
	pushl $30
	jmp isr

.global isr_31
isr_31:
	pushal
	pushl %esp
	pushl $31
	jmp isr

.global isr_32
isr_32:
	pushal
	pushl %esp
	pushl $32
	jmp isr

.global isr_33
isr_33:
	pushal
	pushl %esp
	pushl $33
	jmp isr

.global isr_34
isr_34:
	pushal
	pushl %esp
	pushl $34
	jmp isr

.global isr_35
isr_35:
	pushal
	pushl %esp
	pushl $35
	jmp isr

.global isr_36
isr_36:
	pushal
	pushl %esp
	pushl $36
	jmp isr

.global isr_37
isr_37:
	pushal
	pushl %esp
	pushl $37
	jmp isr

.global isr_38
isr_38:
	pushal
	pushl %esp
	pushl $38
	jmp isr

.global isr_39
isr_39:
	pushal
	pushl %esp
	pushl $39
	jmp isr

.global isr_40
isr_40:
	pushal
	pushl %esp
	pushl $40
	jmp isr

.global isr_41
isr_41:
	pushal
	pushl %esp
	pushl $41
	jmp isr

.global isr_42
isr_42:
	pushal
	pushl %esp
	pushl $42
	jmp isr

.global isr_43
isr_43:
	pushal
	pushl %esp
	pushl $43
	jmp isr

.global isr_44
isr_44:
	pushal
	pushl %esp
	pushl $44
	jmp isr

.global isr_45
isr_45:
	pushal
	pushl %esp
	pushl $45
	jmp isr

.global isr_46
isr_46:
	pushal
	pushl %esp
	pushl $46
	jmp isr

.global isr_47
isr_47:
	pushal
	pushl %esp
	pushl $47
	jmp isr

.global isr_48
isr_48:
	pushal
	pushl %esp
	pushl $48
	jmp isr

.global isr_49
isr_49:
	pushal
	pushl %esp
	pushl $49
	jmp isr

.global isr_50
isr_50:
	pushal
	pushl %esp
	pushl $50
	jmp isr

.global isr_51
isr_51:
	pushal
	pushl %esp
	pushl $51
	jmp isr

.global isr_52
isr_52:
	pushal
	pushl %esp
	pushl $52
	jmp isr

.global isr_53
isr_53:
	pushal
	pushl %esp
	pushl $53
	jmp isr

.global isr_54
isr_54:
	pushal
	pushl %esp
	pushl $54
	jmp isr

.global isr_55
isr_55:
	pushal
	pushl %esp
	pushl $55
	jmp isr

.global isr_56
isr_56:
	pushal
	pushl %esp
	pushl $56
	jmp isr

.global isr_57
isr_57:
	pushal
	pushl %esp
	pushl $57
	jmp isr

.global isr_58
isr_58:
	pushal
	pushl %esp
	pushl $58
	jmp isr

.global isr_59
isr_59:
	pushal
	pushl %esp
	pushl $59
	jmp isr

.global isr_60
isr_60:
	pushal
	pushl %esp
	pushl $60
	jmp isr

.global isr_61
isr_61:
	pushal
	pushl %esp
	pushl $61
	jmp isr

.global isr_62
isr_62:
	pushal
	pushl %esp
	pushl $62
	jmp isr

.global isr_63
isr_63:
	pushal
	pushl %esp
	pushl $63
	jmp isr

.global isr_64
isr_64:
	pushal
	pushl %esp
	pushl $64
	jmp isr

.global isr_65
isr_65:
	pushal
	pushl %esp
	pushl $65
	jmp isr

.global isr_66
isr_66:
	pushal
	pushl %esp
	pushl $66
	jmp isr

.global isr_67
isr_67:
	pushal
	pushl %esp
	pushl $67
	jmp isr

.global isr_68
isr_68:
	pushal
	pushl %esp
	pushl $68
	jmp isr

.global isr_69
isr_69:
	pushal
	pushl %esp
	pushl $69
	jmp isr

.global isr_70
isr_70:
	pushal
	pushl %esp
	pushl $70
	jmp isr

.global isr_71
isr_71:
	pushal
	pushl %esp
	pushl $71
	jmp isr

.global isr_72
isr_72:
	pushal
	pushl %esp
	pushl $72
	jmp isr

.global isr_73
isr_73:
	pushal
	pushl %esp
	pushl $73
	jmp isr

.global isr_74
isr_74:
	pushal
	pushl %esp
	pushl $74
	jmp isr

.global isr_75
isr_75:
	pushal
	pushl %esp
	pushl $75
	jmp isr

.global isr_76
isr_76:
	pushal
	pushl %esp
	pushl $76
	jmp isr

.global isr_77
isr_77:
	pushal
	pushl %esp
	pushl $77
	jmp isr

.global isr_78
isr_78:
	pushal
	pushl %esp
	pushl $78
	jmp isr

.global isr_79
isr_79:
	pushal
	pushl %esp
	pushl $79
	jmp isr

.global isr_80
isr_80:
	pushal
	pushl %esp
	pushl $80
	jmp isr

.global isr_81
isr_81:
	pushal
	pushl %esp
	pushl $81
	jmp isr

.global isr_82
isr_82:
	pushal
	pushl %esp
	pushl $82
	jmp isr

.global isr_83
isr_83:
	pushal
	pushl %esp
	pushl $83
	jmp isr

.global isr_84
isr_84:
	pushal
	pushl %esp
	pushl $84
	jmp isr

.global isr_85
isr_85:
	pushal
	pushl %esp
	pushl $85
	jmp isr

.global isr_86
isr_86:
	pushal
	pushl %esp
	pushl $86
	jmp isr

.global isr_87
isr_87:
	pushal
	pushl %esp
	pushl $87
	jmp isr

.global isr_88
isr_88:
	pushal
	pushl %esp
	pushl $88
	jmp isr

.global isr_89
isr_89:
	pushal
	pushl %esp
	pushl $89
	jmp isr

.global isr_90
isr_90:
	pushal
	pushl %esp
	pushl $90
	jmp isr

.global isr_91
isr_91:
	pushal
	pushl %esp
	pushl $91
	jmp isr

.global isr_92
isr_92:
	pushal
	pushl %esp
	pushl $92
	jmp isr

.global isr_93
isr_93:
	pushal
	pushl %esp
	pushl $93
	jmp isr

.global isr_94
isr_94:
	pushal
	pushl %esp
	pushl $94
	jmp isr

.global isr_95
isr_95:
	pushal
	pushl %esp
	pushl $95
	jmp isr

.global isr_96
isr_96:
	pushal
	pushl %esp
	pushl $96
	jmp isr

.global isr_97
isr_97:
	pushal
	pushl %esp
	pushl $97
	jmp isr

.global isr_98
isr_98:
	pushal
	pushl %esp
	pushl $98
	jmp isr

.global isr_99
isr_99:
	pushal
	pushl %esp
	pushl $99
	jmp isr

.global isr_100
isr_100:
	pushal
	pushl %esp
	pushl $100
	jmp isr

.global isr_101
isr_101:
	pushal
	pushl %esp
	pushl $101
	jmp isr

.global isr_102
isr_102:
	pushal
	pushl %esp
	pushl $102
	jmp isr

.global isr_103
isr_103:
	pushal
	pushl %esp
	pushl $103
	jmp isr

.global isr_104
isr_104:
	pushal
	pushl %esp
	pushl $104
	jmp isr

.global isr_105
isr_105:
	pushal
	pushl %esp
	pushl $105
	jmp isr

.global isr_106
isr_106:
	pushal
	pushl %esp
	pushl $106
	jmp isr

.global isr_107
isr_107:
	pushal
	pushl %esp
	pushl $107
	jmp isr

.global isr_108
isr_108:
	pushal
	pushl %esp
	pushl $108
	jmp isr

.global isr_109
isr_109:
	pushal
	pushl %esp
	pushl $109
	jmp isr

.global isr_110
isr_110:
	pushal
	pushl %esp
	pushl $110
	jmp isr

.global isr_111
isr_111:
	pushal
	pushl %esp
	pushl $111
	jmp isr

.global isr_112
isr_112:
	pushal
	pushl %esp
	pushl $112
	jmp isr

.global isr_113
isr_113:
	pushal
	pushl %esp
	pushl $113
	jmp isr

.global isr_114
isr_114:
	pushal
	pushl %esp
	pushl $114
	jmp isr

.global isr_115
isr_115:
	pushal
	pushl %esp
	pushl $115
	jmp isr

.global isr_116
isr_116:
	pushal
	pushl %esp
	pushl $116
	jmp isr

.global isr_117
isr_117:
	pushal
	pushl %esp
	pushl $117
	jmp isr

.global isr_118
isr_118:
	pushal
	pushl %esp
	pushl $118
	jmp isr

.global isr_119
isr_119:
	pushal
	pushl %esp
	pushl $119
	jmp isr

.global isr_120
isr_120:
	pushal
	pushl %esp
	pushl $120
	jmp isr

.global isr_121
isr_121:
	pushal
	pushl %esp
	pushl $121
	jmp isr

.global isr_122
isr_122:
	pushal
	pushl %esp
	pushl $122
	jmp isr

.global isr_123
isr_123:
	pushal
	pushl %esp
	pushl $123
	jmp isr

.global isr_124
isr_124:
	pushal
	pushl %esp
	pushl $124
	jmp isr

.global isr_125
isr_125:
	pushal
	pushl %esp
	pushl $125
	jmp isr

.global isr_126
isr_126:
	pushal
	pushl %esp
	pushl $126
	jmp isr

.global isr_127
isr_127:
	pushal
	pushl %esp
	pushl $127
	jmp isr

.global isr_128
isr_128:
	pushal
	pushl %esp
	pushl $128
	jmp isr

.global isr_129
isr_129:
	pushal
	pushl %esp
	pushl $129
	jmp isr

.global isr_130
isr_130:
	pushal
	pushl %esp
	pushl $130
	jmp isr

.global isr_131
isr_131:
	pushal
	pushl %esp
	pushl $131
	jmp isr

.global isr_132
isr_132:
	pushal
	pushl %esp
	pushl $132
	jmp isr

.global isr_133
isr_133:
	pushal
	pushl %esp
	pushl $133
	jmp isr

.global isr_134
isr_134:
	pushal
	pushl %esp
	pushl $134
	jmp isr

.global isr_135
isr_135:
	pushal
	pushl %esp
	pushl $135
	jmp isr

.global isr_136
isr_136:
	pushal
	pushl %esp
	pushl $136
	jmp isr

.global isr_137
isr_137:
	pushal
	pushl %esp
	pushl $137
	jmp isr

.global isr_138
isr_138:
	pushal
	pushl %esp
	pushl $138
	jmp isr

.global isr_139
isr_139:
	pushal
	pushl %esp
	pushl $139
	jmp isr

.global isr_140
isr_140:
	pushal
	pushl %esp
	pushl $140
	jmp isr

.global isr_141
isr_141:
	pushal
	pushl %esp
	pushl $141
	jmp isr

.global isr_142
isr_142:
	pushal
	pushl %esp
	pushl $142
	jmp isr

.global isr_143
isr_143:
	pushal
	pushl %esp
	pushl $143
	jmp isr

.global isr_144
isr_144:
	pushal
	pushl %esp
	pushl $144
	jmp isr

.global isr_145
isr_145:
	pushal
	pushl %esp
	pushl $145
	jmp isr

.global isr_146
isr_146:
	pushal
	pushl %esp
	pushl $146
	jmp isr

.global isr_147
isr_147:
	pushal
	pushl %esp
	pushl $147
	jmp isr

.global isr_148
isr_148:
	pushal
	pushl %esp
	pushl $148
	jmp isr

.global isr_149
isr_149:
	pushal
	pushl %esp
	pushl $149
	jmp isr

.global isr_150
isr_150:
	pushal
	pushl %esp
	pushl $150
	jmp isr

.global isr_151
isr_151:
	pushal
	pushl %esp
	pushl $151
	jmp isr

.global isr_152
isr_152:
	pushal
	pushl %esp
	pushl $152
	jmp isr

.global isr_153
isr_153:
	pushal
	pushl %esp
	pushl $153
	jmp isr

.global isr_154
isr_154:
	pushal
	pushl %esp
	pushl $154
	jmp isr

.global isr_155
isr_155:
	pushal
	pushl %esp
	pushl $155
	jmp isr

.global isr_156
isr_156:
	pushal
	pushl %esp
	pushl $156
	jmp isr

.global isr_157
isr_157:
	pushal
	pushl %esp
	pushl $157
	jmp isr

.global isr_158
isr_158:
	pushal
	pushl %esp
	pushl $158
	jmp isr

.global isr_159
isr_159:
	pushal
	pushl %esp
	pushl $159
	jmp isr

.global isr_160
isr_160:
	pushal
	pushl %esp
	pushl $160
	jmp isr

.global isr_161
isr_161:
	pushal
	pushl %esp
	pushl $161
	jmp isr

.global isr_162
isr_162:
	pushal
	pushl %esp
	pushl $162
	jmp isr

.global isr_163
isr_163:
	pushal
	pushl %esp
	pushl $163
	jmp isr

.global isr_164
isr_164:
	pushal
	pushl %esp
	pushl $164
	jmp isr

.global isr_165
isr_165:
	pushal
	pushl %esp
	pushl $165
	jmp isr

.global isr_166
isr_166:
	pushal
	pushl %esp
	pushl $166
	jmp isr

.global isr_167
isr_167:
	pushal
	pushl %esp
	pushl $167
	jmp isr

.global isr_168
isr_168:
	pushal
	pushl %esp
	pushl $168
	jmp isr

.global isr_169
isr_169:
	pushal
	pushl %esp
	pushl $169
	jmp isr

.global isr_170
isr_170:
	pushal
	pushl %esp
	pushl $170
	jmp isr

.global isr_171
isr_171:
	pushal
	pushl %esp
	pushl $171
	jmp isr

.global isr_172
isr_172:
	pushal
	pushl %esp
	pushl $172
	jmp isr

.global isr_173
isr_173:
	pushal
	pushl %esp
	pushl $173
	jmp isr

.global isr_174
isr_174:
	pushal
	pushl %esp
	pushl $174
	jmp isr

.global isr_175
isr_175:
	pushal
	pushl %esp
	pushl $175
	jmp isr

.global isr_176
isr_176:
	pushal
	pushl %esp
	pushl $176
	jmp isr

.global isr_177
isr_177:
	pushal
	pushl %esp
	pushl $177
	jmp isr

.global isr_178
isr_178:
	pushal
	pushl %esp
	pushl $178
	jmp isr

.global isr_179
isr_179:
	pushal
	pushl %esp
	pushl $179
	jmp isr

.global isr_180
isr_180:
	pushal
	pushl %esp
	pushl $180
	jmp isr

.global isr_181
isr_181:
	pushal
	pushl %esp
	pushl $181
	jmp isr

.global isr_182
isr_182:
	pushal
	pushl %esp
	pushl $182
	jmp isr

.global isr_183
isr_183:
	pushal
	pushl %esp
	pushl $183
	jmp isr

.global isr_184
isr_184:
	pushal
	pushl %esp
	pushl $184
	jmp isr

.global isr_185
isr_185:
	pushal
	pushl %esp
	pushl $185
	jmp isr

.global isr_186
isr_186:
	pushal
	pushl %esp
	pushl $186
	jmp isr

.global isr_187
isr_187:
	pushal
	pushl %esp
	pushl $187
	jmp isr

.global isr_188
isr_188:
	pushal
	pushl %esp
	pushl $188
	jmp isr

.global isr_189
isr_189:
	pushal
	pushl %esp
	pushl $189
	jmp isr

.global isr_190
isr_190:
	pushal
	pushl %esp
	pushl $190
	jmp isr

.global isr_191
isr_191:
	pushal
	pushl %esp
	pushl $191
	jmp isr

.global isr_192
isr_192:
	pushal
	pushl %esp
	pushl $192
	jmp isr

.global isr_193
isr_193:
	pushal
	pushl %esp
	pushl $193
	jmp isr

.global isr_194
isr_194:
	pushal
	pushl %esp
	pushl $194
	jmp isr

.global isr_195
isr_195:
	pushal
	pushl %esp
	pushl $195
	jmp isr

.global isr_196
isr_196:
	pushal
	pushl %esp
	pushl $196
	jmp isr

.global isr_197
isr_197:
	pushal
	pushl %esp
	pushl $197
	jmp isr

.global isr_198
isr_198:
	pushal
	pushl %esp
	pushl $198
	jmp isr

.global isr_199
isr_199:
	pushal
	pushl %esp
	pushl $199
	jmp isr

.global isr_200
isr_200:
	pushal
	pushl %esp
	pushl $200
	jmp isr

.global isr_201
isr_201:
	pushal
	pushl %esp
	pushl $201
	jmp isr

.global isr_202
isr_202:
	pushal
	pushl %esp
	pushl $202
	jmp isr

.global isr_203
isr_203:
	pushal
	pushl %esp
	pushl $203
	jmp isr

.global isr_204
isr_204:
	pushal
	pushl %esp
	pushl $204
	jmp isr

.global isr_205
isr_205:
	pushal
	pushl %esp
	pushl $205
	jmp isr

.global isr_206
isr_206:
	pushal
	pushl %esp
	pushl $206
	jmp isr

.global isr_207
isr_207:
	pushal
	pushl %esp
	pushl $207
	jmp isr

.global isr_208
isr_208:
	pushal
	pushl %esp
	pushl $208
	jmp isr

.global isr_209
isr_209:
	pushal
	pushl %esp
	pushl $209
	jmp isr

.global isr_210
isr_210:
	pushal
	pushl %esp
	pushl $210
	jmp isr

.global isr_211
isr_211:
	pushal
	pushl %esp
	pushl $211
	jmp isr

.global isr_212
isr_212:
	pushal
	pushl %esp
	pushl $212
	jmp isr

.global isr_213
isr_213:
	pushal
	pushl %esp
	pushl $213
	jmp isr

.global isr_214
isr_214:
	pushal
	pushl %esp
	pushl $214
	jmp isr

.global isr_215
isr_215:
	pushal
	pushl %esp
	pushl $215
	jmp isr

.global isr_216
isr_216:
	pushal
	pushl %esp
	pushl $216
	jmp isr

.global isr_217
isr_217:
	pushal
	pushl %esp
	pushl $217
	jmp isr

.global isr_218
isr_218:
	pushal
	pushl %esp
	pushl $218
	jmp isr

.global isr_219
isr_219:
	pushal
	pushl %esp
	pushl $219
	jmp isr

.global isr_220
isr_220:
	pushal
	pushl %esp
	pushl $220
	jmp isr

.global isr_221
isr_221:
	pushal
	pushl %esp
	pushl $221
	jmp isr

.global isr_222
isr_222:
	pushal
	pushl %esp
	pushl $222
	jmp isr

.global isr_223
isr_223:
	pushal
	pushl %esp
	pushl $223
	jmp isr

.global isr_224
isr_224:
	pushal
	pushl %esp
	pushl $224
	jmp isr

.global isr_225
isr_225:
	pushal
	pushl %esp
	pushl $225
	jmp isr

.global isr_226
isr_226:
	pushal
	pushl %esp
	pushl $226
	jmp isr

.global isr_227
isr_227:
	pushal
	pushl %esp
	pushl $227
	jmp isr

.global isr_228
isr_228:
	pushal
	pushl %esp
	pushl $228
	jmp isr

.global isr_229
isr_229:
	pushal
	pushl %esp
	pushl $229
	jmp isr

.global isr_230
isr_230:
	pushal
	pushl %esp
	pushl $230
	jmp isr

.global isr_231
isr_231:
	pushal
	pushl %esp
	pushl $231
	jmp isr

.global isr_232
isr_232:
	pushal
	pushl %esp
	pushl $232
	jmp isr

.global isr_233
isr_233:
	pushal
	pushl %esp
	pushl $233
	jmp isr

.global isr_234
isr_234:
	pushal
	pushl %esp
	pushl $234
	jmp isr

.global isr_235
isr_235:
	pushal
	pushl %esp
	pushl $235
	jmp isr

.global isr_236
isr_236:
	pushal
	pushl %esp
	pushl $236
	jmp isr

.global isr_237
isr_237:
	pushal
	pushl %esp
	pushl $237
	jmp isr

.global isr_238
isr_238:
	pushal
	pushl %esp
	pushl $238
	jmp isr

.global isr_239
isr_239:
	pushal
	pushl %esp
	pushl $239
	jmp isr

.global isr_240
isr_240:
	pushal
	pushl %esp
	pushl $240
	jmp isr

.global isr_241
isr_241:
	pushal
	pushl %esp
	pushl $241
	jmp isr

.global isr_242
isr_242:
	pushal
	pushl %esp
	pushl $242
	jmp isr

.global isr_243
isr_243:
	pushal
	pushl %esp
	pushl $243
	jmp isr

.global isr_244
isr_244:
	pushal
	pushl %esp
	pushl $244
	jmp isr

.global isr_245
isr_245:
	pushal
	pushl %esp
	pushl $245
	jmp isr

.global isr_246
isr_246:
	pushal
	pushl %esp
	pushl $246
	jmp isr

.global isr_247
isr_247:
	pushal
	pushl %esp
	pushl $247
	jmp isr

.global isr_248
isr_248:
	pushal
	pushl %esp
	pushl $248
	jmp isr

.global isr_249
isr_249:
	pushal
	pushl %esp
	pushl $249
	jmp isr

.global isr_250
isr_250:
	pushal
	pushl %esp
	pushl $250
	jmp isr

.global isr_251
isr_251:
	pushal
	pushl %esp
	pushl $251
	jmp isr

.global isr_252
isr_252:
	pushal
	pushl %esp
	pushl $252
	jmp isr

.global isr_253
isr_253:
	pushal
	pushl %esp
	pushl $253
	jmp isr

.global isr_254
isr_254:
	pushal
	pushl %esp
	pushl $254
	jmp isr

.global isr_255
isr_255:
	pushal
	pushl %esp
	pushl $255
	jmp isr

